### ISSUE TITLE
segfault when catching sighup very early

### ISSUE THREAD

**Issue by MartinVenconExtAlstom** [aide/aide#100]
Hello,

I noticed the issue on aide 0.17.3.
I got a segfault several times because of an index out of bounds in vlog_msg, on the line 99.
It appeared that a concurrent access in `cache_line` due to a SIGHUP signal caught before `setdefaults_after_config` is causing the problem. When logging the cached lines, an incoherence in the `cached_lines` array causes the segfault, (message level at 0).
A simple disabling of the signals that emit a log (SIGHUP/SIGBUS/SIGUSR1/SIGTERM) was enough to not get the problem anymore. You might want to fix it differently though !

Martin

**Comment by MartinVenconExtAlstom** [comment]
- run aide with --check with an already populated database
- send a bunch of SIGHUP signals to the process right after launching it.
It was our system environment that happened to send a SIGHUP signal to aide, but you can reproduce the issue by doing it manually, with a shell script !

**Comment by hvhaugwitz** [comment]
Thanks, eventually I was able to reproduce the segfault running `while true ; do pkill -SIGHUP aide ; done` and starting `aide` several times.
