### ISSUE TITLE
/tmp filesystem flooded with deleted files

### ISSUE THREAD

**Issue by microwaves** [aide/aide#102]
Hi,

From time to time aide processes consume all the tmp filesystem storage with deleted files.

I could find those files executing:

```
root@ip-xx-xx-xx-xx:~# find /proc/*/fd -ls | grep '(deleted)'
116205968      0 lrwx------   1 root      root           64 Jun 15 09:31 /proc/17547/fd/1 -> /tmp/#10\ (deleted)
116205969      0 lrwx------   1 root      root           64 Jun 15 09:31 /proc/17547/fd/2 -> /tmp/#10\ (deleted)
116205972      0 lrwx------   1 root      root           64 Jun 15 09:31 /proc/18755/fd/1 -> /tmp/#10\ (deleted)
116205973      0 lrwx------   1 root      root           64 Jun 15 09:31 /proc/18755/fd/2 -> /tmp/#10\ (deleted)
root@ip-xx-xx-xx-xx:~# ps auxww | grep 17547
root     17547  0.0  0.0   4632   928 ?        S    05:00   0:00 /bin/sh /usr/bin/aide.wrapper --check
root     21805  0.0  0.0  14860   968 pts/0    S+   09:39   0:00 grep --color=auto 17547
```

After truncating those files, the tmp filesystem is unlocked and the space freed. The processes still keep having issues with those files and locking the storage further, forcing us to kill the processes in order to avoid problems with our production systems.

Process tree:

```
1363 root     /usr/sbin/cron -f
17542 root      \_ /usr/sbin/CRON -f
17545 root          \_ /bin/sh -c /usr/bin/aide.wrapper --check
17547 root              \_ /bin/sh /usr/bin/aide.wrapper --check
18755 root                  \_ /usr/bin/aide --config /var/lib/aide/aide.conf.autogenerated --check
```

The problem impacts in the usability of our system (kubernetes worker node), preventing docker and other system components from creating tmp files.

Could you please advise?

Thanks!

**Comment by hvhaugwitz** [comment]
AIDE does not provide an aide.wrapper script. I assume you are using a Debian based distribution. Please report any issue with the script to your LInux distribution.

In general you can contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any question about the usage of AIDE.
