### ISSUE TITLE
Issue While Building Aide 0.16.2  from Source in Centos7

### ISSUE THREAD

**Issue by JABI786** [aide/aide#103]
Dear All,

I have a requirement to build AIDE 0.16.2 from source in Centos7. But it fails with the following

`[root@centos7-aide-test aide-0.16.2]# ./configure --with-zlib=/usr/lib64/libz.so.1.2.7 
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking for bison... bison -y
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for ld... ld
checking for pkg-config... /usr/bin/pkg-config
checking for library containing syslog... none required
checking for vsyslog... yes
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for byte... no
checking for ushort... yes
checking for ulong... yes
checking for u16... no
checking for u32... no
checking for u64... no
checking size of unsigned short... 2
checking size of unsigned int... 4
checking size of unsigned long... 8
checking size of long long... 8
checking size of unsigned long long... 8
checking for long double with more range or precision than double... yes
checking for ANSI C header files... (cached) yes
checking for strtoll... yes
checking for strtoimax... yes
checking for readdir... yes
checking args to readdir_r... POSIX
checking for stricmp... no
checking for strnstr... no
checking for strnlen... yes
checking for mmap... yes
checking for fcntl... yes
checking for ftruncate... yes
checking for posix_fadvise... yes
checking for asprintf... yes
checking for snprintf... yes
checking for vasprintf... yes
checking for vsnprintf... yes
checking for va_copy... no
checking for __va_copy... no
checking for ISO C99 compliant snprintf... yes
checking for ISO C99 compliant vsnprintf... yes
checking for open/O_NOATIME... no
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for inttypes.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking for pcre_exec in -lpcre... yes
checking for sun-acl-support... no
checking for posix-acl-support... no
checking for selinux-support... no
checking for prelink-support... no
checking for xattr-support... no
checking for e2fsattrs-support... no
checking for lstat64... yes
checking for stat64... yes
checking for readdir64... yes
checking for readdir64_r... yes
checking for LFS ino_t... ino_t
checking for LFS dirent... dirent64
checking size of off_t... 8
checking size of off64_t... 8
checking for mhash_get_block_size in -lmhash... no
configure: WARNING: No mhash means no hmac.
checking for gpg_strerror in -lgpg-error... no
configure: error: You need to have libgpg-error.a installed to use libgcrypt.`

I even compiiled libgpg-error from source , which created the file(libgpg-error.a). But even then the issue persists.

Any help , would be greatly appreciated.
Thanks in advance.

Note:  adding adding  **--disable-static**   to the command works, but then aide does not gzip compress the AIDE database.

**Comment by hvhaugwitz** [comment]
Please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) to ask for help from other CentOS users.

Additionally AIDE v0.16.2 has been released 2 years ago, consider using the latest stable release.

**Comment by elico** [comment]
@hvhaugwitz The latest version of AIDE is probably in the Fedora Rawhide repository  at:
https://src.fedoraproject.org/rpms/aide/tree/rawhide

I have compiled aide for Oracle Linux 8 but I need to find the SRPMs for that.

**Comment by hvhaugwitz** [comment]
The latest (upstream) stable release of AIDE is `v0.17.3` (as of today, see https://github.com/aide/aide/releases).

**Comment by elico** [comment]
What about auto detecting that its not possible to build a static binary?
In most use cases I have seen aide is built as a dynamic binary.

בתאריך שבת, 31 ביולי 2021, 21:51, מאת Hannes von Haugwitz ‏<
***@***.***>:

**Comment by hvhaugwitz** [comment]
> What about auto detecting that its not possible to build a static binary? In most use cases I have seen aide is built as a dynamic binary.

Please discuss this topic in #109.
