### ISSUE TITLE
AIDE returns mixed up error message when rule file contains CRLF characters

### ISSUE THREAD

**Issue by arafatx** [aide/aide#107]
If aide rule file contains a WINDOWS carriage return by accident, AIDE is terminated but return with success code

Let say, I created a new rule called myrule in `/etc/aide/aide.conf.d/myrule`

The content of myrule file above is:

`!/conf$ d`

But this file contains Windows CLRF because I edited this file using Windows then push to SSH for aide. So, AIDE is not able to read the file and gave the following error:

```
aide -c /etc/aide/aide.conf -C
echo "The return status is $?"
')(line: '!/conf$ daide.conf.d/myrule:1: unexpected character: '
```

Output:

`The return status is 0`

Expected output:

It should not return status 0 after terminated itself

There is a way to correct this error by converting the file to unix carriage return but that is another story. The main point here is that AIDE should not return success code (0)

================

AIDE version information:

OS: Debian 11

```
Aide 0.17.3

Compiled with the following options:

WITH_MMAP
WITH_PCRE
WITH_POSIX_ACL
WITH_SELINUX
WITH_XATTR
WITH_CAPABILITIES
WITH_E2FSATTRS
WITH_ZLIB
WITH_MHASH
WITH_AUDIT

Default config values:
config file: <none>
database_in: <none>
database_out: <none>

Available hashsum groups:
md5: yes
sha1: yes
sha256: yes
sha512: yes
rmd160: yes
tiger: yes
crc32: yes
crc32b: yes
haval: yes
whirlpool: yes
gost: yes
stribog256: no
stribog512: no

Default compound groups:
R: l+p+u+g+s+c+m+i+n+md5+acl+selinux+xattrs+ftype+e2fsattrs+caps
L: l+p+u+g+i+n+acl+selinux+xattrs+ftype+e2fsattrs+caps
>: l+p+u+g+i+n+acl+S+selinux+xattrs+ftype+e2fsattrs+caps
H: md5+sha1+rmd160+tiger+crc32+haval+gost+crc32b+sha256+sha512+whirlpool
X: acl+selinux+xattrs+e2fsattrs+caps
```

**Comment by hvhaugwitz** [comment]
Thanks for your bug report. I can reproduce and confirm this issue. Will be fixed in the next release.

**Comment by hvhaugwitz** [comment]
I misread the output in my terminal; I can reproduce the mixed up error message but not the wrong return code:

The follwoing example returns on Debian `sid` the correct return code (`17` `Configuration error`):

```
aide --config-check --before "$(echo -e '!/conf$ d\r\n')" ; echo "The return status is $?"
')(line: '!/conf$ d:1: unexpected character: '
The return status is 17
```
Can you please provide more information how to reproduce the issue with the return code?

**Comment by arafatx** [comment]
@hvhaugwitz hai, feel embarrassed right now because I did not properly create the correct test case. However this issue is only affected the wrapper `aideinit` not `aide`:

So this is reproduceable in `aideinit`:

#!/bin/bash

aideinit --config=/etc/aide/aide.conf -y
retval=$?

echo "This should terminate"

if [ "${retval}" -ne 0 ]; then
    echo "Something is wrong"
    exit 1
fi

echo "This line should not be printed"


Ouput:

This line should not be printed

Expected output:

The last line should not be printed

Since I think aideinit is not maintained in this repository, you can close this issue. Sorry about this.

**Comment by arafatx** [comment]
@hvhaugwitz hai, feel embarrassed right now because I did not properly create the correct test case. However this issue is only affected the wrapper `aideinit` not `aide`:

So this is reproduceable in `aideinit`:

```
#!/bin/bash

aideinit -c /etc/aide/aide.conf -y
retval=$?

if [ "${retval}" -ne 0 ]; then
    echo "Return status is: ${retval}"
    echo "Something is wrong"
    exit 1
fi

echo "This line should not be printed"

```

Ouput:

```
')(line: '!/conf$ daide.conf.d/47_rules:1: unexpected character: '
AIDE --init return code 17
Return status is: 0
This line should not be printed
```

Expected output:

`Something is wrong`


Since I think aideinit is not maintained in this repository, you can close this issue. Sorry about this.

**Comment by hvhaugwitz** [comment]
I keep the issue open for the mixed up error message.

`aideinit` is part of the `aide` Debian package, Please report any issue with the script to the Debian distribution.
