### ISSUE TITLE
AIDE should not care of having a newline character at the end of file

### ISSUE THREAD

**Issue by arafatx** [aide/aide#108]
This might not important but for the sake of error checking readability and sometimes I forgot to put new line in the rule file manually. To demonstrate this:
 
Using a custom rule file `/etc/aide/aide.conf.d/98_custom_rules` as example:

Let say the content of `98_custom_rules` above contains this rule (without a new line)

`!/run/*`

When I run aide, I got a nice error message, that it needs a new line:

`ERROR: /etc/aide/aide.conf.d/98_custom_rules:1: syntax error: unexpected token or end of file, expected newline (line: '!/run/*')`

That is a good and readable error message.

But then, If I put comment at the end of `98_custom_rules` file (without a new line):

```
!/run/*
# TODO
```

When I run aide, I got an error message about syntax error like below 

  `ERROR: /etc/aide/aide.conf.d/99_aide_root:0: syntax error (line: '# TODO')`

Before this, my understanding was the rule file should not contain any comments at the end but actually the error message refers to the missing a newline in the rule file. So the error message here is confusing (it also refers to the different rule file `99_aide_root`).

It is actually not so important to add #comment at the end of rule file. The point here is that AIDE should add a newline automatically in rule file since this is required for rule file to work properly or AIDE should not care of having this newline character as an error.

**Comment by arafatx** [comment]
How do I remove that commit there. That was not related to this issue at all.

**Comment by Zugschlus** [comment]
Would this be better worded as "should not see missing newline at end of file as an error"?

**Comment by arafatx** [comment]
> Would this be better worded as "should not see missing newline at end of file as an error"?

+1 , that would be better but I think it needs this on purpose maybe to break the regex syntax between files using newline character.

**Comment by arafatx** [comment]
> Would this be better worded as "should not see missing newline at end of file as an error"?

+1 , that would be better. 

Also I think AIDE needs this newline on purpose maybe to break regex syntax between files using newline character.
