### ISSUE TITLE
AIDE configuration does not skip linkcount

### ISSUE THREAD

**Issue by tonyqui** [aide/aide#111]
Hello folks,
I have a custom rule implemented in AIDE configuration file:

`NOLINKCOUNT p+u+g+acl+selinux+ftype`
and
`<path-to-watch> NOLINKCOUNT+ANF+ARF`

I expect that the above rule would not check for link count, but AIDE log report:

`Summary:`
` Total number of entries:      94868`
` Added entries:                0`
` Removed entries:              0`
`  Changed entries:              1`

`Changed entries:`
`d   ...    n . . : <path-to-watch>`

`Detailed information about changes:`
`Directory: <path-to-watch>`
` Linkcount: 91                               | 99`

Is there anything wrong in the way the entry has been configured?

**Comment by hvhaugwitz** [comment]
What version of AIDE are you using? Can you please provide the output of the following command (requires AIDE >= 0.17)?

`aide --config <your-config> --log-level rule --path-check "d:<path-to-watch>"`

(Please remove any senstive data from the output)

**Comment by hvhaugwitz** [comment]
I'm not sure if I understand your problem correctly.

If you want to exclude the `linkcount` attribute for all subfolders of `/mnt/var/log` while keeping it for all other files then please try the following configuration (see `RESTRICTED RULES` section of the `aide.conf` man page for details):
```
/mnt/var/log/ d LOGSKIPLINKCOUNTER
/mnt/var/log LOG
```
Note that the `/mnt/var/log` folder itself is only matched by the second rule, hence the `linkcount` attribute is included.

Please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any further question about the usage of AIDE. Meanwhile I close this issue.
