### ISSUE TITLE
bashism in configure script

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#113]
This is Debian Bug #998766, filed by Andrej Shadura

Your package uses configure script with bash features not present in                          
POSIX without explicitly declaring the need to bash shell; this                               
currently works as configure scripts select bash, but when dash enables                       
LINENO support, your configure script will start failing:                                     
                                                                                              
     ../configure: 7171: test: yes: unexpected operator                                       
     checking for pcre_exec in -lpcre... yes                                                  
     checking for posix-acl-support... yes                                                    
     checking for selinux-support... yes                                                      
     ../configure: 7382: test: yes: unexpected operator                                       
     checking for prelink-support... no                                                       
     checking for xattr-support... yes                                                        
     checking for capabilities-support... yes                                                 
     checking for e2fsattrs-support... yes                                                    
     checking for pkg-config... (cached) /usr/bin/pkg-config                                  
     checking pkg-config is at least version 0.9.0... yes                                     
     checking for check >= 0.9.4... no                                                        
     Check not found (testing via 'make check' disabled)                                      
     ../configure: 7848: test: no: unexpected operator                                        
     checking for zlib.h... yes                                                               
     checking for deflate in -lz... yes                                                       
     checking for mhash_get_block_size in -lmhash... yes                                      
     checking for libaudit.h... yes                                                           
     ../configure: 8354: test: yes: unexpected operator                                       
     checking that generated files are newer than configure... done                           
                                                                                              
To test this, you can install dash from experimental and re-run the                           
configure script.                                                                             
                                                                                              
Please replace non-POSIX features with their equivalents to make sure                         
the script runs with dash. Most common ones are usage of == instead of =                      
and for with arrays (not lists).

**Comment by hvhaugwitz** [comment]
fixed in 007eb4f32e8874ce457b4f15d9789c2a9d61731b
