### ISSUE TITLE
Cygwin (Windows) release message

### ISSUE THREAD

**Issue by pdinc-oss** [aide/aide#115]
I am about to publish the announcement message for Cygwin. I am looking for feedback from AIDE team (suggested edits)

from: Jason Pyeron
to: cygwin-announce@cygwin.com
cc:
subject: New: aide v0.17.3-1

FIRST RELEASE
=============

This is the first release of AIDE for Cygwin. It is based on tag v0.17.3 with a patch to support compilation on Cygwin.

If you find bugs and you think they are Cygwin related, please discuss on the Cygwin mailing list and you may open an issue on github (but note Cygwin in the summary). My testing resources are limited to supporting x64, FIPS 140-2 algorithms, and STIG compliance.

Changes and source are tracked at: https://github.com/pdinc-oss/aide.git

RELEASE
=======

The following packages have been uploaded to the Cygwin distribution:

* aide-0.17.3-1

DESCRIPTION
===========

AIDE (Advanced Intrusion Detection Environment) is a file integrity checker and intrusion detection program.

Upstream website: https://aide.github.io/

SUPPORT
=======

Please use the upstream mailing list [https://www.ipi.fi/mailman/listinfo/aide] and issue tracker [https://github.com/aide/aide/issues] for support. I am on the aide mailing list. If the issue is Cygwin related please contact cygwin@cygwin.com . 

-- 
              *** CYGWIN-ANNOUNCE UNSUBSCRIBE INFO ***

If you want to unsubscribe from the cygwin-announce mailing list, look
at the "List-Unsubscribe: " tag in the email header of this message.
Send email to the address specified there. It will be in the format:

cygwin-announce-unsubscribe-you=yourdomain.com@cygwin.com

If you need more information on unsubscribing, start reading here:

http://sourceware.org/lists.html#unsubscribe-simple

Please read *all* of the information on unsubscribing that is available
starting at this URL.

**Comment by hvhaugwitz** [comment]
> If you find bugs and you think they are Cygwin related, please discuss on the Cygwin mailing list and you may open an issue on github (but note Cygwin in the summary). My testing resources are limited to supporting x64, FIPS 140-2 algorithms, and STIG compliance.

Which github issue tracker is meant here? Please do not discuss cygwin issues on the AIDE upstream tracker and use a downstream specific issue tracker instead.

> Please use the upstream mailing list [https://www.ipi.fi/mailman/listinfo/aide] and issue tracker [https://github.com/aide/aide/issues] for support. I am on the aide mailing list. If the issue is Cygwin related please contact [cygwin@cygwin.com](mailto:cygwin@cygwin.com) .

Please remove the aide issue tracker. The issue tracker is for bug reports or feature requests in AIDE and not for support.

Also this topic might be better discussed on the mailing list.

**Comment by pdinc-oss** [comment]
Perfect - changed.

I thought about mailing list - I was on the fence. The notice is archived at https://cygwin.com/pipermail/cygwin-announce/2021-November/010303.html
