### ISSUE TITLE
Migrate from PCRE to PCRE2

### ISSUE THREAD

**Issue by hvhaugwitz** [aide/aide#116]
AIDE still uses obsolete PCRE library and should be migrated to PCRE2[PCRE2]

[PCRE2] https://pcre.org/current/doc/html/

**Comment by Zugschlus** [comment]
will 0.18 be in time for Debian bookworm or would it be a smart idea to backport those patches to 0.17 in Debian?

**Comment by hvhaugwitz** [comment]
Yes, `0.18` will be released in time for Debian Bookworm (scheduled for 2023).
