### ISSUE TITLE
Not able to start AIDE Database Service

### ISSUE THREAD

**Issue by KameshRastogi** [aide/aide#118]
We have successfully installed the rpm packages for AIDE with the other config file for aide. But when trying to initiate the AIDE database using below command , it's running for long but nothing happening and database file didn't appear in path- /var/lib/aide

We are running the command using root user

[root@ssmanager1 system]# systemctl start aideinit.service

Is there any log it would capture and where so we could see and review as why it hangs or waiting for something else and any issues. Please do help.

Thanks,

**Comment by hvhaugwitz** [comment]
Please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any question about the usage of AIDE (and provide more information (e.g. about the version of AIDE you are using or more information about your operating system).
