### ISSUE TITLE
"syntax error" on missing @@endif

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#119]
Hi,

the following code:

```
@@ifdef MARIADB_DBFILES_RE
/@@{MARIADB_DATA}/@@{MARIADB_DBFILES_RE}\.ibd$ f VarFile

/@@{RUN}/mysqld/mysqld\.pid$ f VarFile
!/@@{RUN}/mysqld/mysqld\.sock$ s
```

will issue a generic "syntax error" on the last line of the file.

It would be more helpful if the error message was along the lines of "missing @@endif for @@ if started on line X", or just a plain "missing @@endif".

Greetings
Marc

**Comment by hvhaugwitz** [comment]
With the latest commit the error message is:
```
  ERROR: /tmp/aide.conf:5: syntax error, unexpected end of file, expecting @@else or @@endif (line: '!/@@{RUN}/mysqld/mysqld\.sock$')
```
