### ISSUE TITLE
Please add multithreading support

### ISSUE THREAD

**Issue by hvhaugwitz** [aide/aide#12]
As nowadays AIDE is CPU bound with fast storage (e.g. SSDs) it should benefit from multithreading (e.g. via `pthreads`)

**Comment by rubo77** [comment]
Is there a temporary way to use all CPU cores at least during `aideinit`?

**Comment by hvhaugwitz** [comment]
No, currently there is no way to profit from all CPU cores.

**Comment by A-SOM** [comment]
Could you tell us when this functionality will be implemented?
@hvhaugwitz

**Comment by hvhaugwitz** [comment]
@A-SOM the feature is scheduled/planned for AIDE `v0.18` (currently in development)

**Comment by hvhaugwitz** [comment]
Multithreading support is now available in master branch.

Please give it a try and report back any issues.
