### ISSUE TITLE
Please add a progress bar

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#120]
Hi,

I routinely pipe aide's output through pv --timer so that I have a running clock showing how long aide has been running. It just occurred to me that aide could do that itself. Please consider addint a --timer option.

To be compatible with pv and bar, the clock should be shown on stderr.

Greetings
Marc

**Comment by hvhaugwitz** [comment]
I don't think this should be handled by AIDE. It would imply to re-implement the feature already present in `pv`. The timer output would also overlap with the log output also send to `stderr`.

Therefore I close this issue.

**Comment by hvhaugwitz** [comment]
I plan to add a progress bar to AIDE when `stderr` refers to a terminal.

The progress bar will also contain a timer, hence I reopen and retitle this issue.
