### ISSUE TITLE
Aide coredump when the database file is modified

### ISSUE THREAD

**Issue by yixiangzhike** [aide/aide#122]
We found that the database file is actually an editable file, so we need some security tests.
I tried to attack the database file /var/lib/aide/aide.db.gz by modifying the file content, as a result, aide coredump occurred.

First, I modified the path like this:

@@begin_db                      
\# This file was generated by Aide, version 0.16.2
\# Time of generation was 2022-01-16 15:24:26
@@db_spec name lname attr perm inode uid gid size mtime ctime lcount sha256 sha512 acl xattrs selinux
/root/tmp/testdir 0 12887002045 40700 787649 0 0 4096 MTY0MjMxNzc5Mg== MTY0MjMxNzc5Mg== 2 0 0 POSIX,dXNlcjo6cnd4Cmdyb    3VwOjotLS0Kb3RoZXI6Oi0tLQo=,0 1,security.selinux,dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbWVfdDpzMAA= dW5jb25maW5lZF9    1Om9iamVjdF9yOmFkbWluX2hvbWVfdDpzMA==
**'/root/tmp/testdir/testfile.txt'** 0 16108227517 100600 787650 0 0 9 MTY0MjMxNzc5OQ== MTY0MjMxNzc5OQ== 1 oe/2PWwMOeTYBL    EDbs1pJOff7yzivuvNwxpa1WQJHqo= m1ZCY/RPb4CmuAlS1xxLdBMJmdwcNbSthReFKpxTj/tsi1nm2A9MsgYQ5OxOF2OKnXrt7JEt/FEBJxCb4uldxA    == POSIX,dXNlcjo6cnctCmdyb3VwOjotLS0Kb3RoZXI6Oi0tLQo=,0 1,security.selinux,dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbW    VfdDpzMAA= dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbWVfdDpzMA== 

or

@@begin_db
\# This file was generated by Aide, version 0.16.2
\# Time of generation was 2022-01-16 15:24:26
@@db_spec name lname attr perm inode uid gid size mtime ctime lcount sha256 sha512 acl xattrs selinux
/root/tmp/testdir 0 12887002045 40700 787649 0 0 4096 MTY0MjMxNzc5Mg== MTY0MjMxNzc5Mg== 2 0 0 POSIX,dXNlcjo6cnd4Cmdyb    3VwOjotLS0Kb3RoZXI6Oi0tLQo=,0 1,security.selinux,dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbWVfdDpzMAA= dW5jb25maW5lZF9    1Om9iamVjdF9yOmFkbWluX2hvbWVfdDpzMA==
**a/root/tmp/testdir/testfile.txt** 0 16108227517 100600 787650 0 0 9 MTY0MjMxNzc5OQ== MTY0MjMxNzc5OQ== 1 oe/2PWwMOeTYBLE    Dbs1pJOff7yzivuvNwxpa1WQJHqo= m1ZCY/RPb4CmuAlS1xxLdBMJmdwcNbSthReFKpxTj/tsi1nm2A9MsgYQ5OxOF2OKnXrt7JEt/FEBJxCb4uldxA=    = POSIX,dXNlcjo6cnctCmdyb3VwOjotLS0Kb3RoZXI6Oi0tLQo=,0 1,security.selinux,dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbWV    fdDpzMAA= dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbWVfdDpzMA== 

Coredump info:
Core was generated by `aide --check'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007efd5179bf1e in ?? () from /lib64/libc.so.6
(gdb) bt
#0  0x00007efd5179bf1e in ?? () from /lib64/libc.so.6
#1  0x00007efd5179de6c in malloc () from /lib64/libc.so.6
#2  0x00007efd517a1a8a in strdup () from /lib64/libc.so.6
#3  0x000055569608cf23 in strrxtok (rx=rx@entry=0x555697844b60 "'") at src/gen_list.c:281
#4  0x000055569608d450 in new_seltree_node (tree=tree@entry=0x555696366180, path=path@entry=0x555697844b60 "'", 
    isrx=isrx@entry=0, r=r@entry=0x0) at src/gen_list.c:472
#5  0x000055569608d4f1 in new_seltree_node (tree=tree@entry=0x555696366180, path=path@entry=0x555697844a90 "'", 
    isrx=isrx@entry=0, r=r@entry=0x0) at src/gen_list.c:485
#6  0x000055569608d4f1 in new_seltree_node (tree=tree@entry=0x555696366180, path=path@entry=0x5556978449c0 "'", 
    isrx=isrx@entry=0, r=r@entry=0x0) at src/gen_list.c:485
#7  0x000055569608d4f1 in new_seltree_node (tree=tree@entry=0x555696366180, path=path@entry=0x5556978448f0 "'", 
    isrx=isrx@entry=0, r=r@entry=0x0) at src/gen_list.c:485
#8  0x000055569608d4f1 in new_seltree_node (tree=tree@entry=0x555696366180, path=path@entry=0x555697844820 "'", 
    isrx=isrx@entry=0, r=r@entry=0x0) at src/gen_list.c:485
#9  0x000055569608d4f1 in new_seltree_node (tree=tree@entry=0x555696366180, path=path@entry=0x555697844750 "'", 
    isrx=isrx@entry=0, r=r@entry=0x0) at src/gen_list.c:485
#10 0x000055569608d4f1 in new_seltree_node (tree=tree@entry=0x555696366180, path=path@entry=0x555697844680 "'", 
    isrx=isrx@entry=0, r=r@entry=0x0) at src/gen_list.c:485
#11 0x000055569608d4f1 in new_seltree_node (tree=tree@entry=0x555696366180, path=path@entry=0x5556978445b0 "'", 
    isrx=isrx@entry=0, r=r@entry=0x0) at src/gen_list.c:485
#12 0x000055569608d4f1 in new_seltree_node (tree=tree@entry=0x555696366180, path=path@entry=0x5556978444e0 "'", 
    isrx=isrx@entry=0, r=r@entry=0x0) at src/gen_list.c:485

**The recursive function new_seltree_node can't exit normally, up to the max depth.**

And then, I add a same line to the database file like this:

@@begin_db                      
\# This file was generated by Aide, version 0.16.2
\# Time of generation was 2022-01-16 15:24:26
@@db_spec name lname attr perm inode uid gid size mtime ctime lcount sha256 sha512 acl xattrs selinux
/root/tmp/testdir 0 12887002045 40700 787649 0 0 4096 MTY0MjMxNzc5Mg== MTY0MjMxNzc5Mg== 2 0 0 POSIX,dXNlcjo6cnd4Cmdyb    3VwOjotLS0Kb3RoZXI6Oi0tLQo=,0 1,security.selinux,dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbWVfdDpzMAA= dW5jb25maW5lZF9    1Om9iamVjdF9yOmFkbWluX2hvbWVfdDpzMA==
**/root/tmp/testdir/testfile.txt** 0 16108227517 100600 787650 0 0 9 MTY0MjMxNzc5OQ== MTY0MjMxNzc5OQ== 1 oe/2PWwMOeTYBLED    bs1pJOff7yzivuvNwxpa1WQJHqo= m1ZCY/RPb4CmuAlS1xxLdBMJmdwcNbSthReFKpxTj/tsi1nm2A9MsgYQ5OxOF2OKnXrt7JEt/FEBJxCb4uldxA==     POSIX,dXNlcjo6cnctCmdyb3VwOjotLS0Kb3RoZXI6Oi0tLQo=,0 1,security.selinux,dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbWVf    dDpzMAA= dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbWVfdDpzMA==
**/root/tmp/testdir/testfile.txt** 0 16108227517 100600 787650 0 0 9 MTY0MjMxNzc5OQ== MTY0MjMxNzc5OQ== 1 oe/2PWwMOeTYBLED    bs1pJOff7yzivuvNwxpa1WQJHqo= m1ZCY/RPb4CmuAlS1xxLdBMJmdwcNbSthReFKpxTj/tsi1nm2A9MsgYQ5OxOF2OKnXrt7JEt/FEBJxCb4uldxA==     POSIX,dXNlcjo6cnctCmdyb3VwOjotLS0Kb3RoZXI6Oi0tLQo=,0 1,security.selinux,dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbWVf    dDpzMAA= dW5jb25maW5lZF91Om9iamVjdF9yOmFkbWluX2hvbWVfdDpzMA==

Coredump info:
Core was generated by `aide --check'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055a4baf7f021 in add_file_to_tree (tree=tree@entry=0x55a4bc3b0180, file=file@entry=0x55a4bc3acf60, 
    db=db@entry=1, attr=<optimized out>) at src/gen_list.c:908
908           if (((node->old_data)->attr&~((node->new_data)->attr)&~(ignored_removed_attrs))|(~((node->old_data)->attr)&(node->new_data)->attr&~(ignored_added_attrs))) {
(gdb) bt
#0  0x000055a4baf7f021 in add_file_to_tree (tree=tree@entry=0x55a4bc3b0180, file=file@entry=0x55a4bc3acf60, 
    db=db@entry=1, attr=<optimized out>) at src/gen_list.c:908
#1  0x000055a4baf7f89c in populate_tree (tree=0x55a4bc3b0180) at src/gen_list.c:1207
#2  0x000055a4baf6e221 in main (argc=2, argv=0x7ffeaa512868) at src/aide.c:629
(gdb) p node->old_data
$1 = (struct db_line *) 0x55a4bc3acf60
(gdb) p node->new_data
$2 = (struct db_line *) 0x0
(gdb) 

**The pointer node->new_data is NULL.**

The version is 0.16.2

**Comment by yixiangzhike** [comment]
Thanks for the patch! But the fix does't work for duplicate database entry. The coredump still exist when two same line in the database file.
![图片](https://user-images.githubusercontent.com/17900179/154827849-4b775bfa-6dfe-481b-8bcf-3c3958481920.png)

**Comment by hvhaugwitz** [comment]
I can confirm that the patch is indeed incomplete, I'll look into it.

**Comment by yixiangzhike** [comment]
Thank you! It's OK now.
