### ISSUE TITLE
SIGBUS caught then aide dying when file being sha'ed gets truncated

### ISSUE THREAD

**Issue by rmetrich** [aide/aide#124]
Hello,
I initially reported the issue for Red Hat version of aide as https://bugzilla.redhat.com/show_bug.cgi?id=2062342.
Trying with latest upstream code, it's not better.

aide makes use of mmap() the libgrypt library to calculate the sha sum. If the file being processed gets truncated, this ends up getting a SIGBUS which initially prints a message, then another SIGBUS is sent but not caught anymore (because `catch_mmap` is reinitialized to 0 in signal hander), ending in a fatal error for aide:
~~~
 NOTICE: Caught SIGBUS while mmapping. File was truncated while aide was running?
  ERROR: Caught SIGBUS. Exiting
~~~

Below is a simple reproducer.

1. Create a simple `aide.conf` with one file to be scanned

    ~~~
    database_out = file:/tmp/aide.db
    log_level = debug
    CONTENT = sha512
    
    /tmp/foo CONTENT
    ~~~

2. Create the file to be scanned

    ~~~
    dd if=/dev/zero of=/tmp/foo bs=10M count=1
    ~~~

3. Add a breakpoint in GDB just before `update_md()` call

    ~~~
    $ gdb --args ./aide -c ./aide.conf --init
    [...]
    (gdb) break do_md.c:315
    (gdb) cont
    ~~~

4. At breakpoint, truncate the file

    ~~~
    $ truncate -s 0 /tmp/foo
    ~~~

5. Continue the execution

    ~~~
    (gdb) cont
    ~~~

Result:
~~~
Program received signal SIGBUS, Bus error.
_gcry_sha512_transform_amd64_avx2 () at sha512-avx2-bmi2-amd64.S:327
327		COPY_YMM_AND_BSWAP(Y_0, [INP + 0*32], BYTE_FLIP_MASK)
(gdb) 
Continuing.
 NOTICE: Caught SIGBUS while mmapping. File was truncated while aide was running?

Program received signal SIGBUS, Bus error.
_gcry_sha512_transform_amd64_avx2 () at sha512-avx2-bmi2-amd64.S:327
327		COPY_YMM_AND_BSWAP(Y_0, [INP + 0*32], BYTE_FLIP_MASK)
(gdb) 
Continuing.
  ERROR: Caught SIGBUS. Exiting
[Inferior 1 (process 53312) exited with code 01]
~~~

I'm trying to find a solution for this but don't see any obvious one: it's not possible to _harden_ `mmap()` to protect the file against being truncated (or at least have *aide* own a private copy of the file).

The only solution I see is have some kind of "index" that would record which files have been processed already and re-execute *aide* upon getting SIGBUS while skipping already-processed files.

I'm ready to help propose this code but before that I would like to get your opinion, maybe I'm missing another more obvious solution...

**Comment by permezel** [comment]
Me too!
```console
sloth# uname -a
Darwin sloth 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
sloth# aide --init
open_dir():Operation not permitted: /System/Library/Templates/Data/private/var/db/oah
lstat() failed for /System/Volumes/Data/Library/Caches/com.apple.aned:Operation not permitted
Caught SIGBUS/SEGV while mmapping. File was truncated while aide was running?
Caught SIGBUS/SEGV. Exiting
sloth# aide --help
Aide 0.15.1 

```
The first is not fatal:
```console
sloth# ls -ld@ /System/Library/Templates/Data/private/var/db/oah
drwxr-xr-x@ 2 _oahd  _oahd  64  7 Feb 07:22 /System/Library/Templates/Data/private/var/db/oah
	com.apple.rootless	-1 
```
The second is weird.
```console
sloth# ls -la@ /System/Volumes/Data/Library/Caches/              
ls: com.apple.aned: Operation not permitted
total 0
drwxrwxrwt     9 root           admin    288 25 Feb 09:19 .
drwxr-xr-x    75 root           wheel   2400 18 Feb 20:08 ..
drwxr-xr-x@    3 root           admin     96 18 Feb 20:09 ColorSync
	com.apple.quarantine	   15 
drwxr-xr-x     4 root           admin    128 18 Feb 20:09 Desktop Pictures
drwx--x--x  1078 _iconservices  admin  34496 11 Mar 13:39 com.apple.iconservices.store
drwx------     3 root           admin     96 25 Feb 09:19 com.google.SoftwareUpdate.0
drwxr-xr-x     2 dap            admin     64 19 Feb 10:06 com.microsoft.autoupdate.fba
drwxrwxr-x     3 root           admin     96 18 Feb 20:08 com.microsoft.autoupdate.helper
sloth# find /System/Volumes/Data/Library/Caches/ -print | grep aned
find: /System/Volumes/Data/Library/Caches//com.apple.aned: Operation not permitted
sloth# xattr /System/Volumes/Data/Library/Caches/com.apple.aned    
xattr: [Errno 1] Operation not permitted: '/System/Volumes/Data/Library/Caches/com.apple.aned'
sloth# ls -l@ /System/Volumes/Data/Library/Caches/com.apple.aned 
ls: /System/Volumes/Data/Library/Caches/com.apple.aned: Operation not permitted
```

**Comment by permezel** [comment]
SegV not associated with the weird file:
```console
sloth# aide -c ~dap/xx.conf --init
lstat() failed for /System/Volumes/Data/Library/Caches/com.apple.aned:Operation not permitted

AIDE, version 0.15.1

### AIDE database at /tmp/aide.db initialized.

```

**Comment by permezel** [comment]
It would be nice if the SEGV was caught and ignored, but the offending filename was reported to stderr.

**Comment by rmetrich** [comment]
It's not SEGV (accessing unmapped region), it's more like SIGBUS (bad address) as well, but the code you are using is not latest from Upstream and there was no difference. Now with latest code, only SIGBUS is handled.
Actually the flow is shown below:
1. Initially there is `catch_mmap=1` set just before computing the checksum
2. This makes the signal handler catch properly and print "File was truncated while aide was running" message and finally reset to `catch_mmap=0`
3. The libgcrypt code continues and access bad address again
4. This makes the signal handler execute again but with generic message "Caught SIGBUS. Exiting" and exiting

**Comment by hvhaugwitz** [comment]
Thanks for your bug report.

How often are you affected by files truncated during hash sum calculation?

Unfortunately there is no easy solution here.

The current implementation handles the `SIGBUS` and exits AIDE. This is the simplest and safest solution, though it might make sense to exit on the first `SIGBUS` with a distinct exit code. Also the log level of the log message should be reconsidered.

To handle the `SIGBUS` properly (e.g. via `longjump` etc) AIDE would need to deallocate the memory left over by the hash functions (`mhash` and `gcry_md_write`) and rescan the truncated file. This approach has its own challenges and is hard to implement clean and fail-safe.

Another solution would be to just drop the usage of `mmap` and use `fread` instead, though I don't know how big the performance penalty would be nowadays.

**Comment by rmetrich** [comment]
Hello,
This seems to happen very often when scanning files on NFS for example.
I tried implementing a prototype that uses a worker (as a thread) to perform the computation and kill the worker upon getting SIGBUS. This works well but indeed there is memory allocated by libgrypt so this cannot be a reliable solution.
A reliable solution could be to have a worker as a child process that would kill itself upon SIGBUS, the worker would eat the file to scan on a unix socket or pipe for example. What is unclear to me is if the worker itself can update the database file or have to send the hash result back to main aide process for it to save it.
I'm new to aide so didn't check actually how it works internally.

**Comment by permezel** [comment]
For me, it happens 100% of the time.  I cannot complete an initial scan.  If I rename the .new DB file and try to check, it also happens 100% of the time.

Because it takes hours to get to the point where it dies, and because it fails to indicate which file it is choking on, it is totally non-functioning for me.

I think this is more than an enhancement request.

I've cloned the tree and would fix it myself but I'm neck deep down several rabbit holes trying to get some other things sorted.  Plus it doesn't build on my system (nix pkgs on Darwin): again a trivial fix, but I'm a bit distracted with other issues.

**Comment by permezel** [comment]
Managed to build for darwin.
```console
bash-3.2# /usr/local/bin/aide --version
Aide 0.17.3-32-g1067d1e

Compiled with the following options:

WITH_MMAP
WITH_PCRE2
WITH_ZLIB
WITH_MHASH

Default config values:
config file: /usr/local/etc/aide.conf
database_in: file:/usr/local/etc/aide.db
database_out: file:/usr/local/etc/aide.db.new

Available hashsum groups:
md5: yes
sha1: yes
sha256: yes
sha512: yes
rmd160: yes
tiger: yes
crc32: yes
crc32b: yes
haval: yes
whirlpool: yes
gost: yes
stribog256: no
stribog512: no

Default compound groups:
R: l+p+u+g+s+c+m+i+n+md5+ftype
L: l+p+u+g+i+n+ftype
>: l+p+u+g+i+n+S+ftype
H: md5+sha1+rmd160+tiger+crc32+haval+gost+crc32b+sha256+sha512+whirlpool
X: 
bash-3.2# 
```
Ran a check:
```console
bash-3.2# /usr/local/bin/aide --check
load: 2.41  cmd: aide 92161 running 37.04u 7.60s
load: 2.10  cmd: aide 92161 running 682.22u 413.88s
load: 1.87  cmd: aide 92161 running 1177.42u 728.83s
WARNING: hash calculation: '/System/Library/CoreServices/SystemVersion.plist' has been changed (changed attributes: s+i), hash could not be calculated
WARNING: open_dir() failed for /System/Library/Templates/Data/private/var/db/oah: Operation not permitted
WARNING: hash calculation: open() failed for /System/Volumes/Data/.Spotlight-V100/Store-V2/F5CEB1B8-7FEF-4156-884D-E87D82B656C2/Cache/0000/0000/05bb/96176415.txt: Attribute not found
WARNING: get_file_status: lstat() failed for /System/Volumes/Data/Library/Caches/com.apple.aned: Operation not permitted
load: 6.70  cmd: aide 92161 running 3317.48u 2037.80s
  ERROR: Caught SIGBUS. Exiting
```
I was just checking the progress, and had hit Ctrl-T, and shortly after, it carked. So it ran for >2037 seconds and then carked without producing anything useful like an offending filename.

I should be able to hack it to provide the filename.....

**Comment by rmetrich** [comment]
I think your issue is different here, since you only get the **Caught SIGBUS** message which indicates a SIGBUS was raised outside of the hash function using mmap+gcrypt internally.

**Comment by permezel** [comment]
Working on the hack.  Found a memory leak.  There are two `return` statements ahead of the `free(buf)` which will leak memory.

```console
      buf=checked_malloc(READ_BLOCK_SIZE);
      state->buf = buf;
#if READ_BLOCK_SIZE>SSIZE_MAX
#error "READ_BLOCK_SIZE" is too large. Max value is SSIZE_MAX, and current is READ_BLOCK_SIZE
#endif
      while ((size=TEMP_FAILURE_RETRY(read(filedes,buf,READ_BLOCK_SIZE)))>0) {
    if (update_md(&mdc,buf,size)!=RETOK) {
       log_msg(LOG_LEVEL_WARNING, "hash calculation: update_md() failed for '%s'", line->fullpath);
      close(filedes);
      close_md(&mdc);
      return;
    }
    r_size+=size;
      }

#ifdef WITH_PRELINK
      if (pid) {
        int status;
        (void) waitpid(pid, &status, 0);
        if (!WIFEXITED(status) || WEXITSTATUS(status)) {
         log_msg(LOG_LEVEL_WARNING, "hash calculation: error on exit of prelink child process for '%s'", line->fullpath);
      close(filedes);
      close_md(&mdc);
          return;
        }
      }
#endif
      free(buf);
      close_md(&mdc);
      md2line(&mdc,line);

```

**Comment by permezel** [comment]
> I think your issue is different here, since you only get the **Caught SIGBUS** message which indicates a SIGBUS was raised outside of the hash function using mmap+gcrypt internally.

You might be right.  Still, I feel the need to fix the signal handling in general, and then see where the signal is coming from, and then fix that, and perhaps add threads while I'm at it.  I'm actually still in the eval phase for this s/w.  Not sure if it does what I want it to do.

**Comment by hvhaugwitz** [comment]
@permezel please try `--log-level debug` to see what file causes the SIGBUS and also try to build AIDE with `--without-mmap` configure option and check if the AIDE run finishes without errors.

Regarding the potential memory leak, please file a new bug report for this.

**Comment by hvhaugwitz** [comment]
This issue now has been fixed in master branch.

Please give it a try and report back any issues.
