### ISSUE TITLE
referencial path

### ISSUE THREAD

**Issue by niedomnie** [aide/aide#126]
consider some parameter for using referential path (not absolute one) while generating databases.
It will allow to validate consistency of directories which we do not know upfront where they will be put / install.

**Comment by hvhaugwitz** [comment]
Are you looking for the `root_prefix` option?
``` 
root_prefix (type: path, default: <empty>)
              The  prefix to strip from each file name in the file system before applying the rules and writing to database. AIDE removes a trailing slash from the prefix.  If there are multiple root_prefix lines then the first one is used. This option has no effect
              in compare mode.
```
(from `man aide.conf`)

e.g.:

```
$ mkdir /tmp/test ; touch /tmp/test/a

$ aide --config /dev/null --before "database_out=stdout" --before "/ sha256" --before "root_prefix=/tmp/test" --init 
@@begin_db
# This file was generated by Aide, version 0.17.4
# Time of generation was 2022-03-17 08:55:00
@@db_spec name perm inode attr sha256 
/ 40755 26096 1 0
/a 100644 26097 1073741825 47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
@@end_db

```

**Comment by niedomnie** [comment]
I've got 0.15.1 from centos 7, but upgraded to 0.16, and your command fails @[hvhaugwitz](https://github.com/hvhaugwitz)
Nevertheless thanks for hint.

$ aide --config /dev/null --before "database_out=stdout" --before "/ sha256" --before "root_prefix=/tmp/test" --init
@@begin_db
# This file was generated by Aide, version 0.16
# Time of generation was 2022-03-18 11:03:25
@@db_spec name lname attr perm inode sha256
get_file_status: lstat() failed for /a: No such file or directory
/ 0 1 40555 128 0
[centos@alma53 /]$ aide -version
Aide 0.16

Compiled with the following options:

WITH_MMAP
WITH_PCRE
WITH_POSIX_ACL
WITH_SELINUX
WITH_XATTR
WITH_E2FSATTRS
WITH_LSTAT64
WITH_READDIR64
WITH_ZLIB
WITH_CURL
WITH_GCRYPT
WITH_AUDIT
CONFIG_FILE = "/etc/aide.conf"

**Comment by niedomnie** [comment]
newer versions like 0.17.3 0.17.4 compiled on centos or alma are not possible (zlib not present although installed, with --without-zlib - says libpgp is missing, with 0.17.4 claims similar to pcre library, although is present version 8.42).

So no way to have working aide with that root_prefix.

**Comment by hvhaugwitz** [comment]
> get_file_status: lstat() failed for /a: No such file or directory

There is an issue with accessing the file `/tmp/test/a`.

AIDE v0.16 has been released several years ago, please use the latest upstream version.

Apart from that please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any question about the usage of AIDE. There also might be other CentOS users who can help you with building AIDE from source.
