### ISSUE TITLE
Please add "explicit all" restriction

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#133]
Hi,

I'd like to have a way to express "this rule is deliberately unrestricted" to avoid the "rule is unrestricted" warning in such cases. Maybe a dedicated character "." or "A" could be defined there:

/tmp A Full

Greetings
Marc

**Comment by hvhaugwitz** [comment]
I would suggest a special `None` keyword to represent unrestricted rules. Would that work for you?

**Comment by Zugschlus** [comment]
That works fine. However, other restrictions are a single letter, having a word would maybe be confusing. I am fine with either solution though. Thanks for considering.
