### ISSUE TITLE
Aide processes did not terminate in Redhat Entreprise 7.9

### ISSUE THREAD

**Issue by weetat** [aide/aide#141]
Hi Support

I have OOM issue in all of RedHat Enterprise 7.9 VM.  The 'aide' process are not terminate.
Please advise if this a bug in aide ? Thank you

cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

ps -ef | grep aide
root      12308  12305  5 05:00 ?        00:23:06 /usr/sbin/aide --check
root      18575  18572  0 Oct16 ?        00:23:40 /usr/sbin/aide --check
root      34421  34377  0 11:56 pts/0    00:00:00 grep --color=auto aide
root      43241  43237  0 Oct19 ?        00:22:51 /usr/sbin/aide --check
root      46064  46061  0 Oct18 ?        00:22:53 /usr/sbin/aide --check
root      54028  54024  1 Oct20 ?        00:23:47 /usr/sbin/aide --check
root      68060  68055  0 Oct15 ?        00:22:32 /usr/sbin/aide --check
root      98977  98974  0 Oct17 ?        00:22:59 /usr/sbin/aide --check
root     115617 115613  0 Oct14 ?        00:22:55 /usr/sbin/aide --check

**Comment by hvhaugwitz** [comment]
Please use the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any question about the usage of AIDE. Meanwhile I close this issue for now, feel free to reopen it, if this turns out to be an actual bug in AIDE upstream.
