### ISSUE TITLE
Suggestion: Make a specific file comparison from a previous database

### ISSUE THREAD

**Issue by arafatx** [aide/aide#142]
Hello this is not a bug but a feature suggestion:

Is it possible that we can compare between 2 files based on previous aide.db database? For example, 

using the following example command will do it

`aide --compare-content-diff /path_to_file/test.txt  --compare-from-database-file aide2.db /path_to_file/test.txt`

output:

```
File: /path_to_file/test.txt
 SHA512    : cjc2reNZp7nOd5LgN5nVdJ84ql4nP1vm | Ittnw+c3vKhHZhi0nKAI4ckDCgcfx/fI
             /A49eDjMXx7y8EVRtnr19ZTmr29yf1GD | 5Rin1oeErcn9kc9nPCtdX8VUZuBoL/Z6
             IdI4p/bYQoDHOH9pVqVmeg==         | KMzqE6W1Doq0YUIzE3EGnQ==

or show content change like using `diff` command
```

So, instead of running full scan, we can make a quick comparison of a specific file based on the previous database file (without saving a new database).

Do you think this is a great idea or something is limited that this feature might not be possible?

**Comment by hvhaugwitz** [comment]
I'm not sure if I understand you correctly.

Do you just want to check the a specific file against a database file (without creating a new, updated database)?

If so, just try `aide --check --limt <regex-to-file>`

**Comment by arafatx** [comment]
Ohh, sorry did not realize that it's been there for a long time. Never use that --limt command before. Thank you so much.
