### ISSUE TITLE
AIDE rpm not located in RHEL UBI 8 AppStream repo

### ISSUE THREAD

**Issue by CraigOpie** [aide/aide#149]
Not able to install aide using `yum install aide`.  Verified aide was not located in the AppStream repo using my browser.  Here is a link to the [AppStream repo](https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/appstream/os/Packages/a/).

**Comment by hvhaugwitz** [comment]
AIDE does not provide any downstream packages, please report any issue with downstream packages to your distribution.

In general you can contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any question about the usage of AIDE.
