### ISSUE TITLE
Remove old and obsolete algorithms in favor of modern

### ISSUE THREAD

**Issue by vt-alt** [aide/aide#150]
I'd suggest you remove old (fallen out of cryptographic fashion) and obsolete algorithms like: MD5, SHA1, Tiger, GOST R 34.11-94, and Whirlpool. In favor of something contemporary like SHA-3 or BLAKE2, adding cool algorithms like [BLAKE3](https://github.com/aide/aide/issues/106) would also be good.

For example, you could first remove them from `H`, maybe issue warning, and remove completely in next release.

Also, some distributions removing broken algorithms like MD5, SHA1, so a `configure` option to disable them (while they are here) would be good addition.

Also2, I would suggest `configure` option so select algo for `R` (instead of `md5`), and a list of algos for `H` (really doubtful people need to hash with everything, which is also slow).

**Comment by virtadpt** [comment]
Agreed.  The lack of newer hashing algorithms in AIDE means that it can't be deployed in a lot of systems that are held to a certain level of compliance.

**Comment by Zugschlus** [comment]
Which "newer" hashing algorithms are missing in aide?

Are you aware that aide is just a consumer of libmhash?

**Comment by virtadpt** [comment]
It looks like the ones we need are supported, the aide.conf files were never updated.  My bad.

And no, I was not.

**Comment by icaretoo** [comment]
(lib)mhash does not support BLAKE3 afaik, and is ancient.
https://mhash.sourceforge.net

**Comment by icaretoo** [comment]
> It looks like the ones we need are supported, the aide.conf files were never updated. My bad.
> 
> And no, I was not.

Mhash supports the algorithms:
SHA1, SHA160, SHA192, SHA224, SHA384, SHA512, HAVAL128, HAVAL160, HAVAL192, HAVAL224, HAVAL256, RIPEMD128, RIPEMD256, RIPEMD320, MD4, MD5, TIGER, TIGER128, TIGER160, ALDER32, CRC32, CRC32b, WHIRLPOOL, GOST, SNEFRU128, SNEFRU256

sourcecode last modified 2008-12-08. 
Some decades passed :)

**Comment by hvhaugwitz** [comment]
> (lib)mhash does not support BLAKE3 afaik, and is ancient. 

BLAKE3 support is tracked in issue #106

**Comment by vt-alt** [comment]
@hvhaugwitz Thank you!
