### ISSUE TITLE
Errors on database initialization with AIDE 0.18.1 on macOS

### ISSUE THREAD

**Issue by sconnard** [aide/aide#153]
AIDE generates the following errors:

  ERROR: not implemented in db_writeline_file 33
  ERROR: not implemented in db_writeline_file 33
  ERROR: not implemented in db_writeline_file 33
  ERROR: not implemented in db_writeline_file 33
  ERROR: not implemented in db_writeline_file 33
  ERROR: not implemented in db_writeline_file 33

And the -i database has 6 entries without LFs instead of 11,000+ entries.

**Comment by hvhaugwitz** [comment]
Please provide more information about your setup (OS version, output of `aide --version`) and a minimal aide configuration file to reproduce your problem.

**Comment by sconnard** [comment]
I'm running on a MacBook Pro, 2018 (intel quad-core i7) system running macOS Ventura 13.2.1 (22D68).
I was successfully running AIDE 0.17.4 and only fixed the ifdef deprecations.
My AIDE config is over 200 lines long and it'll take me awhile to come up with a minimal config that fails.  Hopefully tomorrow.

~/wi_aide>aide --version
AIDE 0.18.1

Compile-time options:
use pcre2: mandatory
use pthread: yes
use zlib compression: yes
use POSIX ACLs: no
use SELinux: no
use xattr: no
use POSIX 1003.1e capabilities: no
use e2fsattrs: no
use cURL: yes
use Mhash: no
use GNU crypto library: yes
use Linux Auditing Framework: no
use locale: no
syslog ident: aide
syslog logopt: LOG_CONS
syslog priority: LOG_NOTICE
default syslog facility: LOG_LOCAL0

Default config values:
config file: /usr/local/etc/aide.conf
database_in: file:/usr/local/etc/aide.db
database_out: file:/usr/local/etc/aide.db.new

Available compiled-in attributes:
acl: no
xattrs: no
selinux: no
e2fsattrs: no
caps: no

Available hashsum attributes:
md5: yes
sha1: yes
sha256: yes
sha512: yes
rmd160: yes
tiger: yes
crc32: yes
crc32b: no
haval: no
whirlpool: yes
gost: yes
stribog256: yes
stribog512: yes

Default compound groups:
R: l+p+u+g+s+c+m+i+n+md5+ftype
L: l+p+u+g+i+n+ftype
>: l+p+u+g+s+i+n+ftype+growing
H: md5+sha1+rmd160+tiger+crc32+gost+sha256+sha512+whirlpool+stribog256+stribog512
X:
