### ISSUE TITLE
free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#157]
Hi,

I am running an aide development snapshot on debian bookworm, and on one of my Banana Pi systems (armhf), I get "free(): double free detected in tcache 2" during aide --update.

Unfortunately, rerunning aide --update did not show this behavior again.

Maybe a code inspection is stil in order. But I don't mind if this issue is closed without further action.

Greetings
Marc

**Comment by hvhaugwitz** [comment]
Thanks for your bug report.

Without further information it is very hard to find the cause of the double free (if it is caused by AIDE anyway).

Nevertheless I keep this issue open for a while in case you (or others) can provide more detailed information.
