### ISSUE TITLE
Unexpected character '@' error when rules start with a macro variable whose value begins with a slash

### ISSUE THREAD

**Issue by sconnard** [aide/aide#159]
(This is on a Macintosh using Aide 18.5 but also failed at 17.4. It doesn't fail on Linux at 15.1.)

Conditions:
- initial / on @@define as you would expect for an absolute path
- no / before @@{} usage in a rule
- fails with unexpected character @

@@define TOPDIR /Users/admin/t_aide
@@{TOPDIR} NORMAL
mm2:~/t_aide>aide -i -c test.conf
  ERROR: test.conf:8: unexpected character: '@' (line: '@@{TOPDIR} NORMAL')

**Comment by hvhaugwitz** [comment]
This is expected, the regular expression must start with an explicit '/'.
The change is documented in the NEWS file:
```
Version 0.17 (2021-01-23) -> BACKWARDS INCOMPATIBLE CHANGES:
- (restricted) regular rules must start with literal '/', i.e. the rule cannot begin with a macro variable
```
Please rewrite your configuration as follows:
```
@@define TOPDIR Users/admin/t_aide
/@@{TOPDIR} NORMAL
```
