### ISSUE TITLE
Proper directive for json output?

### ISSUE THREAD

**Issue by munntjlx** [aide/aide#166]
I was wondering what the proper directive for json output looks like? I did add a line like:

```ini
report_url=file:@@{LOGDIR}/aide.log
report_url=stdout
report_format=json
```
Yet it still spits out ascii like its ignoring it. Any proper config examples that show json output with version 0.18.6?

Thomas

**Comment by munntjlx** [comment]
here's my output from the fedora package:

```bash
IDE 0.18.4

Compile-time options:
use pcre2: mandatory
use pthread: yes
use zlib compression: yes
use POSIX ACLs: yes
use SELinux: yes
use xattr: yes
use POSIX 1003.1e capabilities: no
use e2fsattrs: yes
use cURL: yes
use Mhash: no
use GNU crypto library: yes
use Linux Auditing Framework: yes
use locale: no
syslog ident: aide
syslog logopt: LOG_CONS
syslog priority: LOG_NOTICE
default syslog facility: LOG_LOCAL0

Default config values:
config file: /etc/aide.conf
database_in: file:/etc/aide.db
database_out: file:/etc/aide.db.new

Available compiled-in attributes:
acl: yes
xattrs: yes
selinux: yes
e2fsattrs: yes
caps: no

Available hashsum attributes:
md5: yes
sha1: yes
sha256: yes
sha512: yes
rmd160: yes
tiger: yes
crc32: yes
crc32b: no
haval: no
whirlpool: yes
gost: yes
stribog256: yes
stribog512: yes
```

**Comment by hvhaugwitz** [comment]
Just set `report_format` before the corresponding `report_url` option, as documented in `aide.conf` manual page:
> The following report options are available (to take effect they have to be set before report_url)

In general please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any question about the usage of AIDE.
