### ISSUE TITLE
configure: error: AIDE requires mhash or libcrypt for hashsum calculation

### ISSUE THREAD

**Issue by Michael-Arguello-Imprivata** [aide/aide#167]
Hello,
I'm trying to run the instructions in the README file:
        $ ./configure
        $ make
        $ make install
This is on a fresh CentOS7 minimal system. I installed the requirements listed in the README file. When I run ./configure, I get the following error:
configure: error: AIDE requires mhash or libcrypt for hashsum calculation

I double-checked, and I have the following packages installed:
libgcrypt-1.5.3-14.el7.x86_64
libgcrypt-devel-1.5.3-14.el7.x86_64

I also installed mhash: mhash-0.9.9.9-10.el7.x86_64, but I still get the error.
Any ideas?
Thanks!

**Comment by hvhaugwitz** [comment]
Please use the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) to ask for help on compilation issues (and include information about the version of AIDE you try to compile).

**Comment by 1583771831** [comment]
how to fix it?
