### ISSUE TITLE
Customising AIDE daily report title

### ISSUE THREAD

**Issue by RZR7332** [aide/aide#168]
Hello,

Forgive me if this is a stupid question, but I cannot find an easy or obvious answer to this.

I have set AIDE to run every morning and send the report output via mail to an external mailbox. However, every mail comes in with the same title, which can make it difficult to determine at a glance which report is for which day.

Is there a way to include the date in the mail/report title to make this easily distinguishable?

**Comment by hvhaugwitz** [comment]
AIDE does not provide any cron job script. I assume you are using a Debian based distribution, that ships AIDE with a cron/systemd timer job. Please report any issue with the cron script to your LInux distribution.

In general you can contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any question about the usage of AIDE.

**Comment by Zugschlus** [comment]
And before you file a bug in Debian, please try reading /usr/share/doc/aide-common/README.Debian and/or /etc/default/aide and search for MAILSUBJ.

**Comment by RZR7332** [comment]
> And before you file a bug in Debian, please try reading /usr/share/doc/aide-common/README.Debian and/or /etc/default/aide and search for MAILSUBJ.

This is exactly what I needed, thank you! The answer is in /etc/default/aide - add the extra info into the line and problem solved.
