### ISSUE TITLE
Installing in Termux 

### ISSUE THREAD

**Issue by b9Joker108** [aide/aide#169]
I am trying to install aide in Termux.

I git cloned the repository.

I made sure I had all the dependencies installed.

I executed: sh ./autogen.sh

I had an error regarding the AC_MSG_ERROR macro in configure.ac

So, I added the following line to line five in configure.ac:

m4_pattern_allow([AC_MSG_ERROR])

I then executed: sh ./configure 

And got this error output:

./configure: 7322: Syntax error: word unexpected (expecting ")")

I tried everywhichway to fix the syntax error, but no success. 

I could do with some assistance.

**Comment by hvhaugwitz** [comment]
Please use the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) to ask for help on compilation issues (and include information about the version of AIDE you try to compile as well as the whole output of the commands).
