### ISSUE TITLE
Debian 11 Bullseye there more than 4 Virtual DRM-Devices. 

### ISSUE THREAD

**Issue by Benotto** [aide/aide#170]
Hi,
on Debian 11 Bullseye there more than 4 Virtual DRM-Devices. 

f =.... mci.H..   : /run/udev/data/+drm:card0-Virtual-5
f =.... mci.H..   : /run/udev/data/+drm:card0-Virtual-6
f =.... mci.H..   : /run/udev/data/+drm:card0-Virtual-7
f =.... mci.H..   : /run/udev/data/+drm:card0-Virtual-8

root@xxxxxx:/var/log# cat /etc/aide/aide.conf.d/31_aide_rsyslog
---> @@define RUNUDEVVIDEO card0-(e?DP|HDMI-A|Virtual)-[1234]
-- CHANGE -> @@define RUNUDEVVIDEO card0-(e?DP|HDMI-A|Virtual)-[12345678]

THX 
Tobias Fischer

**Comment by hvhaugwitz** [comment]
Please report any issue with the aide Debian package to the Debian BTS (https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=aide)

In general you can contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any question about the usage of AIDE.
