### ISSUE TITLE
excluding directories sometimes excludes the content as well

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#24]
Hi,

see the following aide.conf:

```
database=file:/home/mh/aide/aide.db
database_out=file:/home/mh/aide/aide.db.new
database_new=file:/home/mh/aide/aide.db.new
gzip_dbout=no
summarize_changes=yes
grouped=no

!/(etc|var|usr|home|dev|proc|sys)
!/run/udev/(data|links|tags|watch)$ d
/ sha256+sha512+rmd160+haval+gost+crc32+tiger+p+u+g+ftype+s+b+n+i+acl+xattrs+e2fsattrs+selinux
```

When running aide --init with this configuration no contents of /run/udev/data/ is included in the database. Removing the !/run/udev/... line, /run/udev/data's contents is there.

The use case is getting an aide notice if an unexpected file shows up in /run/udev/data by excluding the directory entries themseves, and the usual contents of /run/udev/data/. That way, if a file shows up that isn't "the usual contents", aide would report that.

Greetings
Marc

**Comment by hvhaugwitz** [comment]
Thanks for your bug report.

Do you want to exclude the directories which exactly match `/run/udev/(data|links|tags|watch)$` or additionally all subdirectories?

Nevertheless I can reproduce your issue and confirm it is a bug.

**Comment by Zugschlus** [comment]
Just the one directory.
It works if one proceeds to explicitly include the contents again, such as
```
!/path/to/dir$ d
/path/to/dir/ Full
```

**Comment by Zugschlus** [comment]
I can confirm that in the example use case, the contents of /run/udev/data is now in the database.
