### ISSUE TITLE
How do you build this?

### ISSUE THREAD

**Issue by jonasv** [aide/aide#27]
Hi,

having problem compiling this from the source, it feels like configure is broken:
(centos 7 x64)

checking for mhash_get_block_size in -lmhash... no
configure: WARNING: No mhash means no hmac.
checking for gpg_strerror in -lgpg-error... no
configure: error: You need to have libgpg-error.a installed to use libgcrypt.

However, I have both libgcrypt and libgcrypt-devel installed. Also downloaded and installed libgpg-error from source, I still can't build it with default settings, so I had to use --without-gcrypt .

Then during compile time at the end I think linking has failed

aide-0.16.1]# gcc -std=gnu99 -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -W -Wall -g -g -O2   -static  -o aide src/aide.o src/base64.o src/be.o src/commandconf.o src/compare_db.o src/conf_lex.o src/conf_yacc.o src/db.o src/db_disk.o src/db_file.o src/db_lex.o src/db_list.o src/db_sql.o src/do_md.o src/error.o src/gen_list.o src/getopt1.o src/getopt.o src/list.o src/md.o src/snprintf.o src/symboltable.o src/util.o  -lm -lpcre -pthread
/bin/ld: cannot find -lm
/bin/ld: cannot find -lpcre
/bin/ld: cannot find -lpthread
/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

So how do you build this ? Maybe this builds on specific OS like debian etc ?

Thanks,

**Comment by jonasv** [comment]
Nevermind, I found that I was missing some static libs.. However, just FYI that problem with configure remains!

Thanks

**Comment by i108** [comment]
@jonasv Can you shed some light on how you got this to compile?

**Comment by hvhaugwitz** [comment]
@i108 Please share your compilation issues on the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) to get help from other users.

**Comment by jonasv** [comment]
> @jonasv Can you shed some light on how you got this to compile?

yum -y install glibc-static # try this, I think this resolved my issue, but if it wont work, then please let me know and I'll check history on right machine on Monday

**Comment by nutanv** [comment]
libgpg-error.a is not to be found even after I installed 
libgpg-error-1.36 or gcrypt

my attempts to configure this builds are failing. Any help would be appreciated. I can share additonal logs if that helps.
