### ISSUE TITLE
Weird aide errors

### ISSUE THREAD

**Issue by inuitviking** [aide/aide#3]
I have some weird issues, and I'm not entirely sure why or how this has happened.
Here's the information I have so far.
I've installed aide using:
`apt install aide`

When I run `aide -v`, it shows that `CONFIG_FILE` is in `/usr/local/etc/aide.conf`, but the actual configuration file lies in `/etc/aide/aide.conf`.

When I run `aide -C` it comes with this error:
`Couldn't open file /usr/local/etc/aide.db for reading`
Looking into that directory, the file doesn't exist.

I also tried to check the DB with the actual config file with `aide --config=/etc/aide/aide.conf -C` and got this error:
```
38:Error in expression:acl
Configuration error
```
And line 38 in the configuration file:
```
InodeData = OwnerMode+n+i+Size+l+acl+xattrs+e2fsattrs+selinux
```
I see it mention `acl` in the string.
Is my installation completely messed up?

If you must know, it's a debian 6.0.10

**Comment by hvhaugwitz** [comment]
Debian provides some wrapper scripts around AIDE. Please check the manual pages for `aideinit` and `aide.wrapper`.

Apart from that, your Debian release is very outdated and no longer receives security updates. You should update to a recent release, which also contains a newer AIDE version.

If you have more questions about the usage of AIDE, please contact the [AIDE mailing list](https://www.ipi.fi/mailman/listinfo/aide).
