### ISSUE TITLE
check against remote database

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#31]
This is https://sourceforge.net/p/aide/feature-requests/24/

It would be cool if you could specify the url of a remote database either on the command line or in the config file that would be used as the base for comparison. Rather than storing the database on protected media, you could generate it, then move to another server.

**Comment by hvhaugwitz** [comment]
AIDE has http, https and ftp database backend support via curl (`--with-curl` ./configure option).

Please check if this satisfies your future request. If so please consider to close this issue. Otherwise please point out what is missing.

**Comment by elico** [comment]
@hvhaugwitz I have not seen any example of usage.
A configuration example with curl will help.
Thanks.

**Comment by hvhaugwitz** [comment]
@elico eg `database_in=http://example.com/aide.db`

**Comment by elico** [comment]
@hvhaugwitz Is there any way to upload a new DB file into a url?

**Comment by hvhaugwitz** [comment]
No, AIDE has no write support for the `http`, `https` and `ftp` database backend.
