### ISSUE TITLE
Please support /dev/null as input database

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#35]
This is https://sourceforge.net/p/aide/feature-requests/19/

Hi,

for debugging, it might be useful to use /dev/null as
input _and_ as output database. This is currently not
allowed, but makes sense in this special case.

Please consider allowing this special case.

Greetings
Marc

**Comment by hvhaugwitz** [comment]
Since v0.16.2 `/dev/null` is supported as output database.

What is the use case for using `/dev/null` as input database and what is the difference to just initialize the database with `--init`?

**Comment by Zugschlus** [comment]
You get a report as if you had an empty database before. And it's faster than --init.

Greetings
Marc

**Comment by hvhaugwitz** [comment]
Using `/dev/null` as input database currently gives you a warning about missing `db_spec`:
```
mkdir /tmp/test
aide --config /dev/null --before database=file:/dev/null --before database_attrs=E --before root_prefix=/tmp/test --before '/ R' --check
File database must have one db_spec specification
Start timestamp: 2020-12-23 20:58:32 +0100 (AIDE 0.16.1)
AIDE found differences between database and filesystem!!
Root prefix: /tmp/test

Summary:
  Total number of entries:      1
  Added entries:                1
  Removed entries:              0
  Changed entries:              0

---------------------------------------------------
Added entries:
---------------------------------------------------

d++++++++++++++++: /

End timestamp: 2020-12-23 20:58:32 +0100 (run time: 0m 0s)
```

The warning will be removed in the next release of AIDE.
