### ISSUE TITLE
output options

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#36]
This is https://sourceforge.net/p/aide/feature-requests/21/

different output options, such has a mysql database or even csv/tsv data would be easier to parse to send to a database with an external command.

This would definitely need the output to have a structure that is similar throughout the different types of alerts that are written by aide.

**Comment by hvhaugwitz** [comment]
There is #18 that requests JSON as output format. Would that fit your needs?

**Comment by Zugschlus** [comment]
yes.
