### ISSUE TITLE
improved reporting and logging

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#41]
This is https://sourceforge.net/p/aide/feature-requests/28/

The issue is your report format is next to impossible to normalize within a SEIM architecture.

Please add to the aide.conf (example) variations for logging:

i.e.
@@define DBDIR /var/lib/aide
@@define LOGDIR /var/log/aide
database=file:@@{DBDIR}/aide.db.gz
database_out=file:@@{DBDIR}/aide.db.gz
gzip_dbout=yes
verbose=5
report_url=stdout
report_url=file:@@{LOGDIR}/aide.log
report_url=syslog:LOG_AUTH

Also; please add a comment on how to append to the log instead of creating a new one.

I would recommend a better format for logging (vice reporting).

I would recommend the following:

log_url = (Take the same paramters)
log_format = syslog_IEFT, JSON, csv

I would recommend on syslog_IEFT format that you have individual lines for:

something like this:
AIDE: Start timestamp: 2016-05-17 22:02:37 : Total number of files: 40872 : Added files:0 : Removed files: 0 : Changed files: 2
AIDE: Change timestamp: 2016-05-17 22:02:37 : File: /etc/aide.conf : Inode : 133 , 907946
AIDE: Change timestamp: 2016-05-17 22:02:37 : File: /etc/fstab : Inode : 907941 , 907945 : RMD160 : 6ESZcmz1AkxzWEiCHTeInV07QeI= , Iv6sOdBI1J3a6BbDBhHelIe3NAI= SHA256 : PPxCVeCdH3tHYPT+rfY2PTwIvOepG2kF , zPMueGeaJVa/JOtwI8mrxPjOHk16J9/V
AIDE: Added timestamp: 2016-05-17 22:02:37 : File: /etc/cron.daily/test.file
AIDE: End timestamp: 2016-05-17 22:02:37 : Total number of files: 40872 : Added files:0 : Removed files: 0 : Changed files: 2

Format JSON it would be one line for all.
Some syslog takes JSON in syslog per line so that would be good.
If logging JSON format to a directory; one json file per aide run (preferably compressed)

Also in your default aide.conf:

[Perhaps one for Debian and one for RHEL variations]

You may want to add as a default:

Directories:
/etc/sysctl.d
/etc/modprobe.d
/etc/audit/rules.d

Files
/etc/default/grub

**Comment by captain118** [comment]
This would be awesome!

**Comment by makefu** [comment]
Hey, i'd really love to have such feature as the report format is presumably great for being read by humans but not by machines.
Right now it seems to be necessary to build a state machine to get some sense out of the output.
I'd be glad if i could help with the implementation or at least testing of such feature!

**Comment by hvhaugwitz** [comment]
This feature request is a bit messy and confuses report and log output. So let me try to line up a bit:

Log messages are written to `stderr` by default  A `log_url` option can be discussed in #20.

The possible values for `report_url` are listed and documented in the `aide.conf` manual page, please open a new issue if something is missing there.

A `report_append` config option has been added recently in AIDE `0.17`.

The `json` report format is handled in #18.

That leaves `IEFT` report format for this issue. Can you please specify in more detail how the report output should look like?

**Comment by Zugschlus** [comment]
I cannot say anything abot this, I just cut&pasted the issue from Sourceforge.

**Comment by hvhaugwitz** [comment]
@captain118 @makefu as you reacted with :+1: to this issue, can you please read my last comment and specify in more detail what is still missing in AIDE and how the report should look like?

**Comment by makefu** [comment]
Hi, i'd love to see aide reporting results in json format so they can be forwarded to a SOC and checked/alerted there if changes occurred which were not planned.

Right now the `json` format in #18 is the most relevant to get this working as the IETF format can be solved by a syslog forwarding agent (rsyslog,syslog-ng)

**Comment by elico** [comment]
@makefu I wrote an experimental log file conversion utility in ruby at #18 .
Please let me know if there is something specific missing in it.

**Comment by hvhaugwitz** [comment]
I close this feature request now in favour of #18; if there is still something missing regarding `IEFT` report format, please open a new issue.
