### ISSUE TITLE
Please consider adding an optional warning for a rule that doesn't have a restriction selector

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#44]
Hi,

restricted selection lines are a vast improvement of aide rule flexibility. I would love to encourage people ot use the feature. For myself, I am checking my rules with

`awk '{if ($2 !~ '/[fdlsbcp]/') { print }}' FS=" "`

but wouldnt it be nice to have aide check for that and have it issue a warning in higher verbosity levels.

Grüße
Marc

**Comment by hvhaugwitz** [comment]
I'm not sure if such an option is really useful. Mostly you have at least one general unrestricted rule (eg `/ R`) that would raise a permanent warning on each run.

**Comment by Zugschlus** [comment]
That is not meant as a helpful thing for regular runs, but for one-shot checks of rule sets before shipping.

**Comment by hvhaugwitz** [comment]
What about an option like `config_check_warn_on_unrestricted_rules` that raises a warning during `--config-check- when enabled?

**Comment by Zugschlus** [comment]
Looks good. It would be great if there would be a possibility to detect this special case in a surrounding script without having to grep / parse the output.
