### ISSUE TITLE
SELinux Shows AIDE Trying to Access SSSD Socket

### ISSUE THREAD

**Issue by OldTimeNESter** [aide/aide#46]
I'm getting SELinux denials indicating that /usr/sbin/aide is trying to access a socket used by SSSD: the socket path is /var/lib/sss/pipes/nss. I posted this on Serverfault last week and was advised to bring it up here. Here is the link to that post which contains more information:

https://serverfault.com/questions/971435/selinux-aide-trying-to-access-sssd-socket/971580#971580

**Comment by RichieB2B** [comment]
As mentioned on Stackoverflow, please report this with your Linux distribution. Probably RedHat or CentOS? We do not package aide for any distribution.
