### ISSUE TITLE
Please add an option to ignore e2fsattrs that cannot be set or removed

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#47]
Hi,

I am getting reports like this:
    d   ...   .  .. E: /var/cache/apt-cacher-ng/debian/dists/bullseye/main/binary-i386/Packages.diff    
    Directory: /var/cache/apt-cacher-ng/debian/dists/bullseye/main/binary-i386/Packages.diff            
      E2FSAttrs: -----------------e---            | --------------I--e---                               

According to man chattr, I means that a directory is indexed using hashed trees. This looks to me like some filesystem internal which cannot be set manually. If my assessment is true, I think that this should not be reported by aide (or at least excludeable).

Greetings
Marc

**Comment by hvhaugwitz** [comment]
You can use `report_ignore_e2fsattrs=EhI`to ignore changes of the compression error (E), huge file (h), indexed directory (I) attributes in the report.

An option to ignore changes of e2fsattrs that cannot be set or removed using `chattr` would indeed make sense.

**Comment by Zugschlus** [comment]
Should that be in the default config upstream or in Debian?

**Comment by hvhaugwitz** [comment]
The 'report_ignore_e2fsattrs=EhI` option should be added in Debian for now.

For the new option I'm still thinking about the default value.
