### ISSUE TITLE
exclude regex beginning with word doesn't work

### ISSUE THREAD

**Issue by arafatx** [aide/aide#49]
I'm trying to exclude the following file autogenerated with the name begin with session_

!/home/root/tmp/^session_.+$

example: session_jdskaj293829jdks, session_92ujds29030jsd

and the system still notifies new file added or changed beginning with the name session_ at that directory.

Am I missing something?

**Comment by hvhaugwitz** [comment]
Your regular expression is wrong. `^` matches the starting position within a string, however the string starts with `/home` not with `session_`. Apart from that AIDE adds an implict  `^` in front of each regular expression (as documented in the `aide.conf` manual page).

Please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any further question about the usage of AIDE.

**Comment by arafatx** [comment]
Thanks for pointing out that AIDE adds implicit ^. I couldn't find this manual in my existing aide.conf. Solved. TQVM
