### ISSUE TITLE
Please add an option to append to report url

### ISSUE THREAD

**Issue by ekelson-bcove** [aide/aide#5]
Whenever we run `aide --update` to create a new aide db, the aide.log file in /var/log/aide is overwritten.  This presents a challenge a I'd like to maintain a record of aide activities.  Is there a setting to cause this log to be appended vs replaced?

**Comment by hvhaugwitz** [comment]
No, currently there is no such option, but you can use `savelog` to rotate the log file before re-running AIDE.
