### ISSUE TITLE
multi-directory exclusion

### ISSUE THREAD

**Issue by fire002** [aide/aide#51]
Hi. how to make multi-directory exclusion on aide?
I tried `!/var/www/*/data/www/assets/*` on config, but when creating the database I see errors:
get_file_status: lstat() failed for /var/www/site1/data/www/assets/captcha5d8085ae7dd54.png: No such file or directory
get_file_status: lstat() failed for /var/www/site2/data/www/assets/captcha5d8098ee56a1a.png: No such file or directory

**Comment by hvhaugwitz** [comment]
Your regular expression is wrong. If you want to exclude all (regular) files in the `assets/` directories try to use `!/var/www/.*/data/www/assets f`.

Please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any further question about the usage of AIDE.
