### ISSUE TITLE
Support multiple incremental databases

### ISSUE THREAD

**Issue by KOLANICH** [aide/aide#54]
I mean creating databases often and then storing only diffs between the adjacent databases. Then it should be possible to see the picture of what happens in the system in time.

**Comment by hvhaugwitz** [comment]
I don't think this should be handled by AIDE. It would imply to re-implement tools like `diff` that can be used directly on the plain text database files.

If you solely want to see what happens in time on the system you also could just keep the reports of each AIDE run.

Therefore I close this issue.

**Comment by KOLANICH** [comment]
>It would imply to re-implement tools like diff that can be used directly on the plain text database files.

Not a good idea. Diff is optimized for diffing text files. The states of FS are not text files. It is structured info and it should be diffed in a structured way.

>If you solely want to see what happens in time on the system you also could just keep the reports of each AIDE run.

I don't need AIDE runs reports. I need analysis what happens. For each space increase I should know how much each app is responsible for it and if I should delete that bloatware and install something else developed by more sane (who don't claim that increase in size of an app by 60 MiB per year is normal and expectable and completely OK for them) devs.

**Comment by Zugschlus** [comment]
Is --compare what you need/want? If not, please make your self a bit more clear.
