### ISSUE TITLE
Support the following use case: space eating stealthy malware detection

### ISSUE THREAD

**Issue by KOLANICH** [aide/aide#55]
A strange thing is going on my phone. I have run out of free space. I have written some shell scripts doing the comparison, and quicly detected some benign apps responsible for eating. But it doesn't explain something. According to the history of size snapshots almost almost every small file (there are lot of them) has gains some hudreds of KiB. Even the ones that were not expected to change - the ones created by me that I have not touched between the snapshots. That's very strange. So I can imagine a malware that may use other apps files as its redundant distributed filesystem which data cannot be destroyed without either writing a special utility or wiping the all the valuable data infected.

But we can try to detect the changes. It is likely that the malware just adds the data into the gaps of files of suitable formats, if there is not enough gaps, it can create one. Often apps like databases have their data pages aligned, so the following approach may work: hash not the whole file, but its parts of certain size. Then detect the changed parts and show the user hexdump of them. Or analyse their content for entropy level and how it matches the entropy level of the unchanged part of file. Or even better, implement plugins parsing various formats headers and finding out if any gaps have been created.

**Comment by hvhaugwitz** [comment]
This is out of scope of AIDE. AIDE scans the file system on file level not the files on page level. It reports when the content (or an attribute) of a file has been changed. It does not show what parts within the file has been changed. Hence I close this issue.
