### ISSUE TITLE
do_md(): open() ... : Permission denied

### ISSUE THREAD

**Issue by knzudgt** [aide/aide#56]
I just installed AIDE 0.16 on a Ubuntu 18.04 LTS server via `apt`.
Whenever I run `sudo aide -c /etc/aide/aide.conf --check` I get a long list of items like the following:

```
do_md(): open() for /var/lib/lxcfs/cgroup/blkio/blkio.reset_stats failed: Permission denied
do_md(): open() for /var/lib/lxcfs/cgroup/blkio/system.slice/blkio.reset_stats failed: Permission denied
do_md(): open() for /var/lib/lxcfs/cgroup/blkio/system.slice/accounts-daemon.service/blkio.reset_stats failed: Permission denied
...
```
The same list is mailed to me daily after the cron job is runned.
Does anyone of you know what is it all about?

**Comment by hvhaugwitz** [comment]
Please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any question about the usage of AIDE.

**Comment by knzudgt** [comment]
@hvhaugwitz could you check please the link in your message? It redirects to Roundcube login.

**Comment by hvhaugwitz** [comment]
@knzudgt Thanks for the hint. I informed the list maintainer and report back as soon as the page is available again.
