### ISSUE TITLE
Checksums or capture hash when file is created

### ISSUE THREAD

**Issue by nutanv** [aide/aide#57]
Hi, I am testing with Aide 0.15.1 on Oracle Linux 7 (fully app compliant with RHEL); I've been wanting to add a feature in FIM (aide) where whenever a file is created in specific directories; aide should capture md5 or sha256. I can see hashes in aide.db file, but when those hashes do not appear to be either md5 or sha256.
Also, when "aide --check" is executed after initial snapshot is created. aide.log has similar hashes in them which do not appear to be md5.

Steps to Recreate:
1. Install aide from local yum repo.
`yum install aide`
2. create fim.conf with contents-
`
database=file:/var/lib/aide/aide.db
database_out=file:/var/lib/aide/aide.db.new
database_new=file:/var/lib/aide/aide.db.new
GETIOC=p+i+n+u+g+s+m+md5
/home/nutan GETIOC
`
3. initialise
`aide -c fim.conf --init --verbose`
4. rename new.db to make it initial snapshot
`mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db`
5. Create and Make changes to test file in /home/nutan directory : "testfile"
6. Run aide to check on changes.
`aide -c fim.conf --check --verbose`
9 Note the results on screen and in aide.log. It has MD5 hash value but the value is not actually MD5.
`
---------------------------------------------------
Changed files:
---------------------------------------------------

changed: /home/nutan
changed: /home/nutan/aide
changed: /home/nutan/testfile
---------------------------------------------------
Detailed information about changes:
---------------------------------------------------
Directory: /home/nutan
 Mtime    : 2019-10-21 15:15:59              , 2019-10-21 15:39:44
Directory: /home/nutan/aide
 Size     : 22                               , 65
 Mtime    : 2019-10-21 15:17:42              , 2019-10-21 15:22:42

File: /home/nutan/testfile
 Size     : 253                              , 280
 Mtime    : 2019-10-21 14:37:25              , 2019-10-21 15:39:44
 MD5      : ivtmaHWScBWzGlhyjiFWtQ==         , M+HNNIcqB/9cIClhZgVK9g==`
----------
My Ask
----------
It appears the MD5 is encoded in some form; Given the "==" I tried decoding those using base64, but that too did not reveal actual MD5.
what config chage can be done retrieve actual MD5 of the file in aide.log; 
Also, while we talk of MD5 in this example, SHA256 has same issues.

**Comment by hvhaugwitz** [comment]
From the `aide(1)` manual page:

> The checksums in the database and in the output are by default base64 encoded (see also `report_base16` option).  To decode them you can use the following shell command:
>
> `echo <encoded_checksum> | base64 -d | hexdump -v -e '32/1 "%02x" "\n"'`

Please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any further question about the usage of AIDE.
