### ISSUE TITLE
SHA256 and SHA512 are not valid Checksums 

### ISSUE THREAD

**Issue by jithinandoor** [aide/aide#58]
Hi, I am testing with Aide 0.15.1 on Oracle Linux 7 (fully app compliant with RHEL); I've been wanting to add a feature in FIM (aide) where whenever a file is created in specific directories; aide should capture SHA512 or sha256. I can see hashes in aide.db file. I ran "echo <encoded_checksum> | base64 -d | hexdump -v -e '32/1 "%02x" "\n”’ to get the original data however its doesn't seems to be valid and the length of the SHA512 is much shorter than expected
value from AIDE: +SN7oBJJ7EyLh0uxddVyc8RSI5ojh46X
value post running the base64 decode command: 
f9237ba01249ec4c8b874bb175d57273c452239a23878e97
Bit length: | 192
Character length: | 48

Steps to Recreate:

    Install aide from local yum repo.
    yum install aide
    create fim.conf with contents-
    database=file:/var/lib/aide/aide.db database_out=file:/var/lib/aide/aide.db.new database_new=file:/var/lib/aide/aide.db.new GETIOC=p+i+n+u+g+s+m+sha256+sha512 /home/nutan GETIOC
    initialise
    aide -c fim.conf --init --verbose
    rename new.db to make it initial snapshot
    mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db
    Create and Make changes to test file in /home/nutan directory : "testfile"
    Run aide to check on changes.
    aide -c fim.conf --check --verbose

**Comment by hvhaugwitz** [comment]
Can you please try again using the latest version of AIDE (v0.16.2).

There was an issue with cut off checksums in the report that has been fixed in c863a020775cd4e9d631cfb43c478920e2c2f0e4 about 9 years ago.

**Comment by jithinandoor** [comment]
Thanks for that !!

**Comment by hvhaugwitz** [comment]
Can you please report back if your issue is solved in the latest release?

**Comment by jithinandoor** [comment]
The issue is resolved in 16.2. !!
