### ISSUE TITLE
Is its possible to do daily check

### ISSUE THREAD

**Issue by spacecabbie** [aide/aide#59]
Hello,
I am wondering is it possible to do a daily report on changes. But at the sametime do a weekly / monthly / yearly change report.
I figure i can script it by --update and constantly making copies of the db is this the recommended way ? or is there another solution.
ps. Not a biggie but is there a nice 
gui or em,ail template ?

**Comment by hvhaugwitz** [comment]
Yes, the recommended way to do daily checks is via a script. Some distributions (eg `Debian`) even provide a `cron.daily` script to do daily checks.

Apart from that AIDE does not provide a GUI (see also #53)

Please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any further question about the usage of AIDE.
