### ISSUE TITLE
multi directory inclusion

### ISSUE THREAD

**Issue by sabrish72** [aide/aide#66]
Hi ,
How to make multi directory inclusion on aide.
I wanted to monitor all files/directories under
I added a line to config `/var/lib/docker/overlay2/.*/diff/  CONTENT_EX` but its not working. Can you please tell me if i am doing in right way.

Also when i add `/var/lib/docker/overlay2/ CONTENT_EX` its absolutely  working fine.

**Comment by hvhaugwitz** [comment]
This should work since AIDE v0.16.

What version of AIDE are you using?

**Comment by sabrish72** [comment]
- we are using v0.15.1 . As its default with yum.

**Comment by hvhaugwitz** [comment]
AIDE v0.15.1 has been released in 2010 (almost 10 years ago), please use the latest upstream version of AIDE.
