### ISSUE TITLE
cron.daily in /run/aide

### ISSUE THREAD

**Issue by iamspector** [aide/aide#68]
This is more of a question than an issue of a bug or something. 

Recently I had a problem on one of my systems with aide consuming all of the space in /run.

After each daily cron run it creates temporary cron.daily directory in /run/aide.

My /run is mounted with the size of 796MB and after a week of daily runs this cron.daily directories consumed all of the space.

`root@my-server:/run# du -sch aide/* | grep -vE '^0|K'

99M aide/cron.daily
100M aide/cron.daily.old.1MV71MCH2b
100M aide/cron.daily.old.6Vli33Nc11
99M aide/cron.daily.old.CECwDp5c8s
100M aide/cron.daily.old.HxbiTwfaIW
100M aide/cron.daily.old.lZEPrqsxkR
794M total`

I couldn't find any exact information on why are this directories even created in the first place and how can I control its size or the number of /run/aide/cron.daily.* directories to keep.

Recently I made a workaround by mounting /run/aide separatly as another tmpfs, but I don't think that's how it is supposed to work.

I am writing to ask if it is natural behaviour for aide's cron.daily runs and, if not, how can I configure it via aide's configuration files to adjust the number of cron.daily.* directories so that they won't use all the space they are given?

**Comment by hvhaugwitz** [comment]
AIDE does not provide any cron job script. I assume you are using a Debian based distribution, that ships AIDE with a script in `/etc/cron.daily/aide` . Please report any issue with the cron script to your LInux distribution.

In general you can contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any question about the usage of AIDE.
