### ISSUE TITLE
what is default group X?

### ISSUE THREAD

**Issue by jauling** [aide/aide#70]
I don't see the `X` rule listed in the latest manpages. What is its definition?

**Comment by hvhaugwitz** [comment]
The `X` group is listed in the `aide.conf` man page under the `DEFAULT GROUPS` section:

>  `X:   acl+selinux+xattrs+e2fsattrs (if groups are explicitly enabled)`

Please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any further question about the usage of AIDE.
