### ISSUE TITLE
Keep getting weird email from AIDE even it is not running

### ISSUE THREAD

**Issue by arafatx** [aide/aide#74]
So based on the closed issue here: #73 

I wrote a script and do a neat check for aide to run properly in my hosting.  but I keep getting unfinished running script alert due to the bug about db_spec and the email I got has the same content and has the same date and time stamp . In your opinion, where the email came from? Why I keep getting aide alert message when I have no running script. I wrote this issue more details here: https://webmasters.stackexchange.com/questions/130405/getting-the-same-email-at-the-same-time-from-rootserver-myserver-com-not-sure

Just want to have clarification if this a known issue.

Information:

Aide 0.16

Compiled with the following options:

WITH_MMAP
WITH_PCRE
WITH_POSIX_ACL
WITH_SELINUX
WITH_XATTR
WITH_E2FSATTRS
WITH_LSTAT64
WITH_READDIR64
WITH_ZLIB
WITH_CURL
WITH_GCRYPT
WITH_AUDIT
CONFIG_FILE = "/etc/aide.conf"

CentOS 8

**Comment by Zugschlus** [comment]
aide doesn't send e-mail. You must have some software running aide and creating it. Check your logs to find out.

**Comment by hvhaugwitz** [comment]
As said in #73 please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) if you have any question about the usage of AIDE.

Use GitHub issues for actual bugs in AIDE (and if you can provide a minimal configuration to reproduce your issue).

**Comment by arafatx** [comment]
Solved this yesterday. Due to the problem about db_spec, AIDE did not complete the script and causes the script to send large attachment (without any filter from aide.conf), so exim had trouble retrying to send the email with large attachment and it was stuck for many days. So, I found out that it was in one of the exim mail input folders. Clear up the input folders and the spam email is gone. TQ.
