### ISSUE TITLE
Error running /etc/cron.daily/aide manually

### ISSUE THREAD

**Issue by rubo77** [aide/aide#76]
When I start this as root on the console (Debian buster with XEN 4.11), I get this errror:

```
$ /etc/cron.daily/aide
/etc/cron.daily/aide: line 79: update-aide.conf: command not found
/etc/cron.daily/aide: line 21: onexit: command not found

**Comment by Zugschlus** [comment]
This is most probably a Debian issue, as upstream aide doesn't come with a cron script. Please report Debian issues with the Debian BTS, and file user requests with the aide mailing list.

update-aide.conf is in /usr/sbin, so you should have this in your path. root should have that in their path.

I notice that your shell prompt is $ and not #, are you sure that you have an interactive root session with correct environment?

Hannes, I think this can be closed here.
