### ISSUE TITLE
ignore errors in @@ifdef?

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#84]
Hi,

I tried to write an universal aide.conf file:

```
@@define AIDE_VERSION_017 017

@@ifdef AIDE_VERSION_017
log_level=warning
report_level=changed_attributes
@@else
verbose = 6
@@endif
```

This doesnt work with the new parser, since it flags the verbose = 6 in the unreachable part of the condition as an error nevertheless.

Same thing happens with escape issues that have been legal in older aide but are no longer legal in later aide, such as [\\] which was a literal backslash in old aide but escapes the ] in new aide (causing a syntax error). This error can be avoided by rewriting the regep, so the issue is not as painful here.

I can understand how this might happen, and I also understand that aide might bombs out with the error well before the @@ifdef is processed. I would, however, love if it would be possible to have a possibility to write files that can be read both by old and new aide, avoiding the need to synchronize rule and code updates.

Greetings
Marc

**Comment by hvhaugwitz** [comment]
You should be able to achieve the desired behaviour by using the `@@include` directive and include a pre-0.17 file that contains the old options.

Apart from that `[\]` was already a syntax error before, but now AIDE errors out during config parsing on regular expression errors.

**Comment by Zugschlus** [comment]
Using @@include would mean exploding one file to three files for every point where an incompatibility occurs, which is the case for the main options and rules where a backslash is in the file name. Possible, but so ugly that I won't go down this rule and rather go for more preprocessing.
