### ISSUE TITLE
please document format of detail report

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#95]
Hi,

I have the following report:

```
File: /var/lib/apt/lists/security.debian.org_dists_buster_updates_InRelease                                                
 Perm      : -rw-r--r--                       | -rw-------                                                                 
 Uid       : 0                                | 106                                                                        
 ACL       : A: user::rw-                     | A: user::rw-                                                               
             A: group::r--                    | A: group::---                                                              
             A: other::r--                    | A: other::---                                                              
```
Since the file is actually root:root 644, I guess that the version read from the database is in the right column, while the version found on the live system is the left column. I didn't find any place in the aide or aide.conf man pages that explicitly says that.

Please consider verifying that my guess is correct and documenting this in a manual page.

Greetings
Marc

**Comment by hvhaugwitz** [comment]
Actually the left column shows the old value (from the `database_in` file) and the right column shows the new value (from the file system).

**Comment by Zugschlus** [comment]
*sigh* Research shows that apt actually changes those InRelease files from root root 644 to apt:root 600 on apt update and then back to root root 644. aide must have caught this file just in the few seconds that the interm state was seen. I am reluctant to write a rule allowing this change though.
