### ISSUE TITLE
Return code of "aide --check" in scripts

### ISSUE THREAD

**Issue by Rot127** [aide/aide#97]
I have aide (ver. 0.16.2) on my OpenBSD 6.8 installation which runs every X hours (via cron) in a tiny script.
The script simply executes `aide --check || cat /<pathto>/aide-report | mail -s <e-mail>`.

The thing is, the mail is sent always. Regardless of the filesystem state.
Running
```
# aide --check
# echo $?
0
```
returns 0, but it doesn't seem to do this in the script.

I also tried to do the check in an if statement (comparing by `== 0`, `-eq 0` or not comparing by all) or by storing the return value in a variable. Tested it in ksh and bash, but nothing changed.

Is this a bug in aide? Or am I really so stupid to write 10+ shell scripts incorrectly.

**Comment by hvhaugwitz** [comment]
Can you please provide more information about your issue? What does `aide` report, when you expect a zero return code?

Additionally `aide` v0.16.2 has been released 3 years ago, please use the latest stable release.

**Comment by Rot127** [comment]
It writes the result into a file (which works fine). The file is specified via the `result_url=file://<path_to_file>` option in `aide.conf`.

Unfortunately `v0.16.2` is the last version provided by the OpenBSD package manager. Yet, I tried to avoid building `aide`. But will do it and report back.

**Comment by Rot127** [comment]
The update to v0.17.3 fixed it. Next time I will update to the new version first.
